import Header from '@/components/layout/Header';
import HeroCarousel from '@/components/home/HeroCarousel';
import LatestNews from '@/components/home/LatestNews';
import InterviewsSection from '@/components/home/InterviewsSection';
import Sidebar from '@/components/layout/Sidebar';
import Footer from '@/components/layout/Footer';
import CategoriesSection from '@/components/home/CategorySection';
import { getPosts, getInterviewPosts } from "../lib/wordpress";
import PremiumBanner from '@/components/common/PremiumBanner';
import TrendingBar from '@/components/common/TrendingBar';
import MosaicHighlights from '@/components/common/MosaicHighlights';
import MaceioShowcase from '@/components/home/MaceioShowcase';
import ViralStrip from '@/components/home/ViralStrip';
import InstagramVideoBanner from '@/components/common/InstagramVideoBanner';
import SponsorBanner from '@/components/common/SponsorBanner';
import TopStoryBanner from '@/components/common/TopStoryBanner';

export const revalidate = 61;

export default async function Home() {
  const feedPosts = await getPosts(150); const interviews = await getInterviewPosts(40);
  const today='2026-09-18T07:00:00-03:00';
  const pesquisaPost={id:'datafolha-1809',slug:'datafolha-lula-flavio-1809',title:{rendered:'Datafolha: Lula tem 39% e Flávio Bolsonaro 36% no primeiro turno'},excerpt:{rendered:'Pesquisa divulgada nesta quinta-feira mostra os dois principais candidatos em empate técnico; no segundo turno, Lula aparece com 46% e Flávio com 44%.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-700',featured_image:'https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5894.jpg',href:'https://www1.folha.uol.com.br/poder/2026/09/datafolha-lula-e-flavio-bolsonaro-vao-intensificar-campanha-por-voto-util-para-tentar-vencer-no-1o-turno.shtml'};
  const tsePost={id:'tse-1809',slug:'tse-registros-candidatura-1809',title:{rendered:'Justiça Eleitoral rejeita cerca de 1,2 mil registros de candidatura'},excerpt:{rendered:'TSE informa que 99% dos 20,9 mil pedidos apresentados para as eleições de outubro já foram analisados.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-blue-700',featured_image:'https://agenciabrasil.ebc.com.br/sites/default/files/styles/1170x700/public/thumbnails/image/urna_eletronica_0.jpg',href:'https://agenciabrasil.ebc.com.br/politica/noticia/2026-09/justica-eleitoral-rejeita-cerca-de-12-mil-registros-de-candidatura'};
  const selicPost={id:'selic-1809',slug:'selic-1375-1809',title:{rendered:'Selic cai para 13,75% ao ano após quinta redução consecutiva'},excerpt:{rendered:'Copom reduziu a taxa básica em 0,25 ponto percentual e reforçou cautela diante das incertezas no cenário externo.'},date:today,published_at:today,created_at:today,category:'Economia',categorySlug:'economia',categoryColor:'bg-green-700',featured_image:'https://agenciabrasil.ebc.com.br/sites/default/files/thumbnails/image/banco_central_3.jpg',href:'https://agenciabrasil.ebc.com.br/economia/noticia/2026-09/bc-reduz-juros-basicos-para-1375-ao-ano'};
  const cldfPost={id:'cldf-1809',slug:'cldf-novas-regioes-1809',title:{rendered:'CLDF aprova criação das regiões administrativas de 26 de Setembro e Ponte Alta'},excerpt:{rendered:'Deputados distritais aprovaram a criação das novas regiões administrativas e defenderam mais autonomia e investimentos locais.'},date:today,published_at:today,created_at:today,category:'Distrito Federal',categorySlug:'distrito-federal',categoryColor:'bg-green-700',featured_image:'https://www.cl.df.gov.br/documents/5744638/0/CLDF.jpg',href:'https://www.cl.df.gov.br/-/cldf-aprova-criacao-das-regioes-administrativas-de-26-de-setembro-e-ponte-alta'};
  const paulaPost={id:'paula-1809',slug:'paula-belmonte-entrevista-tv-voz-2309',title:{rendered:'TV Voz de Brasília entrevista Paula Belmonte na quarta-feira, às 10h'},excerpt:{rendered:'Deputada participa de entrevista online e ao vivo em 23 de setembro. Foi à Voz de Brasília que ela revelou pela primeira vez sua candidatura ao Buriti.'},date:today,published_at:today,created_at:today,category:'Entrevista',categorySlug:'politica',categoryColor:'bg-green-700',featured_image:'https://www.cl.df.gov.br/documents/5744638/0/Paula+Belmonte.jpg',href:'https://www.vozdebrasilia.com.br/noticia/cafe-com-politica-paula-belmonte-participa-de-entrevista-ao-vivo-nesta-sexta-21',ctaLabel:'▶ Ver entrevista'};
  const curyPost={id:'cury-1809',slug:'augusto-cury-programa-1809',title:{rendered:'Augusto Cury propõe mandato de oito anos no STF e semipresidencialismo'},excerpt:{rendered:'Programa de governo reúne 18 projetos e prevê mudanças institucionais, além da criação de uma diplomacia econômica.'},date:today,published_at:today,created_at:today,category:'Política',categorySlug:'politica',categoryColor:'bg-blue-700',featured_image:'https://agenciabrasil.ebc.com.br/sites/default/files/thumbnails/image/augusto_cury.jpg',href:'https://agenciabrasil.ebc.com.br/politica/noticia/2026-09/augusto-cury-propoe-mandato-de-oito-anos-no-stf-e-semipresidencialismo'};
  const chuvaPost={id:'chuvas-1809',slug:'chuvas-sul-sudeste-1809',title:{rendered:'Inmet prevê retorno de chuvas ao Sul e Sudeste neste fim de semana'},excerpt:{rendered:'Mudança no padrão atmosférico favorece transporte de ar quente e úmido e aumenta as instabilidades a partir desta sexta-feira.'},date:today,published_at:today,created_at:today,category:'Brasil',categorySlug:'brasil',categoryColor:'bg-blue-700',featured_image:'https://agenciabrasil.ebc.com.br/sites/default/files/thumbnails/image/chuva_0.jpg',href:'https://agenciabrasil.ebc.com.br/geral/noticia/2026-09/inmet-preve-final-de-semana-de-chuvas-nas-regioes-sul-e-sudeste'};
  const curated=[pesquisaPost,tsePost,selicPost,cldfPost,paulaPost,curyPost,chuvaPost];
  const posts=[...curated,...feedPosts.filter((p:any)=>!['datafolha','tse','selic','cldf','paula-belmonte','augusto-cury'].some(n=>String(p?.slug||'').includes(n)))];
  const norm=(p:any)=>`${p?.title?.rendered??''} ${p?.excerpt?.rendered??''} ${p?.category??''} ${p?.categorySlug??''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const heroPosts:any[]=curated;
  const isMaceio=(p:any)=>/maceio|alagoas|pajucara|ponta verde|praia do frances|maragogi|sao miguel dos milagres/.test(norm(p)); const maceioPosts=posts.filter(isMaceio);
  const categories=[{title:'Política',category:'politica'},{title:'Distrito Federal',category:'distrito-federal'},{title:'Economia',category:'economia'},{title:'Turismo',category:'turismo'},{title:'Gastronomia',category:'gastronomia'},{title:'Saúde',category:'saude'},{title:'Tecnologia',category:'tecnologia'},{title:'Esportes',category:'esportes'},{title:'Internacional',category:'internacional'},{title:'Cultura',category:'cultura'}];
  return <div className="min-h-screen bg-gray-50"><Header/><main className="pt-16"><TrendingBar posts={posts}/><div className="pt-4 space-y-4"><SponsorBanner sponsor="petrobras"/><div className="max-w-[1400px] mx-auto px-4"><TopStoryBanner href={pesquisaPost.href} kicker="ELEIÇÕES 2026 • 18 DE SETEMBRO" title="Datafolha: Lula 39% e Flávio Bolsonaro 36%" excerpt="Os dois principais candidatos seguem em empate técnico. A disputa entra na reta final antes do primeiro turno de 4 de outubro." image={pesquisaPost.featured_image}/></div><SponsorBanner sponsor="snaider"/></div><div className="mt-4"><HeroCarousel posts={heroPosts}/></div><InstagramVideoBanner/><div className="bg-white pt-8"><div className="max-w-[1400px] mx-auto px-4"><LatestNews posts={posts}/></div></div><div className="mt-4"><PremiumBanner variant={0}/></div><div className="mt-6"><SponsorBanner sponsor="visao"/></div><ViralStrip/><MosaicHighlights posts={posts}/><div className="mt-6 mb-2"><PremiumBanner variant={3}/></div><div className="mt-4 mb-2"><SponsorBanner sponsor="lunardi"/></div><div className="max-w-[1400px] mx-auto px-4 py-8"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-10">{categories.map((c)=><CategoriesSection key={c.category} title={c.title} category={c.category}/>)}</div><aside className="lg:col-span-1"><div className="lg:sticky lg:top-24"><Sidebar/></div></aside></div></div><div className="mb-2"><PremiumBanner variant={1}/></div><div className="mt-4 mb-2"><SponsorBanner sponsor="coreto"/></div>{maceioPosts.length>0&&<MaceioShowcase/>}<div className="bg-gray-50 py-8"><div className="max-w-[1400px] mx-auto px-4"><InterviewsSection posts={interviews}/></div></div><div className="mt-4 mb-2"><SponsorBanner sponsor="kumon"/></div><div className="mt-2 mb-10"><PremiumBanner variant={2}/></div></main><Footer/></div>;
}
