import Header from '@/components/layout/Header';
import HeroCarousel from '@/components/home/HeroCarousel';
import LatestNews from '@/components/home/LatestNews';
import InterviewsSection from '@/components/home/InterviewsSection';
import Sidebar from '@/components/layout/Sidebar';
import Footer from '@/components/layout/Footer';
import CategoriesSection from '@/components/home/CategorySection';
import { getPosts, getInterviewPosts } from "../lib/wordpress";
import PremiumBanner from '@/components/common/PremiumBanner';
import TrendingBar from '@/components/common/TrendingBar';
import MosaicHighlights from '@/components/common/MosaicHighlights';
import MaceioShowcase from '@/components/home/MaceioShowcase';
import ViralStrip from '@/components/home/ViralStrip';
import InstagramVideoBanner from '@/components/common/InstagramVideoBanner';
import SponsorBanner from '@/components/common/SponsorBanner';
import TopStoryBanner from '@/components/common/TopStoryBanner';

export const revalidate = 61;

export default async function Home() {
  const feedPosts = await getPosts(150); const interviews = await getInterviewPosts(40);
  const today='2026-09-17T12:00:00-03:00';
  const roneyPost={id:'roney-nemer-2026',slug:'roney-nemer-candidato-distrital-2026',title:{rendered:'Rôney Nemer disputa vaga de deputado distrital pelo DF'},excerpt:{rendered:'Rôney Nemer concorre pelo PP ao cargo de deputado distrital nas Eleições 2026.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://dados.agenciasertao.com/json/v1/eleicoes/2026/fotos/70002538503.jpg',href:'https://operamundi.uol.com.br/eleicoes-2026/candidatos/roney-nemer/'};
  const celinaPost={id:'celina-1709',slug:'celina-leao-agenda-df-1709',title:{rendered:'Celina Leão segue agenda no DF em meio ao debate sobre o BRB'},excerpt:{rendered:'A governadora do Distrito Federal e candidata à reeleição segue cumprindo agendas públicas e de campanha enquanto o BRB permanece no centro do debate político local.'},date:today,published_at:today,created_at:today,category:'Distrito Federal',categorySlug:'distrito-federal',categoryColor:'bg-green-700',featured_image:'https://www.agenciabrasilia.df.gov.br/wp-conteudo/uploads/2025/01/WhatsApp-Image-2025-01-01-at-12.25.32.jpeg',href:'https://www.agenciabrasilia.df.gov.br/'};
  const paulaPost={id:'paula-1709',slug:'paula-belmonte-entrevista-tv-voz-2309',title:{rendered:'Paula Belmonte será entrevistada pela TV Voz de Brasília na quarta-feira, às 10h'},excerpt:{rendered:'A candidata ao Governo do Distrito Federal volta à TV Voz de Brasília para uma entrevista ao vivo na quarta-feira, 23 de setembro, às 10h.'},date:today,published_at:today,created_at:today,category:'Entrevista',categorySlug:'politica',categoryColor:'bg-green-700',featured_image:'https://www.cl.df.gov.br/documents/5744638/0/Paula+Belmonte.jpg',href:'https://www.vozdebrasilia.com.br/noticia/cafe-com-politica-paula-belmonte-participa-de-entrevista-ao-vivo-nesta-sexta-21',ctaLabel:'Ver entrevista anterior'};
  const posts=[celinaPost,paulaPost,roneyPost,...feedPosts.filter((p:any)=>!['roney-nemer','celina-leao','paula-belmonte'].some(n=>String(p?.slug||'').includes(n)))];
  const norm=(p:any)=>`${p?.title?.rendered??''} ${p?.excerpt?.rendered??''} ${p?.category??''} ${p?.categorySlug??''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const heroPosts:any[]=[
    {id:'lula-1709',slug:'lula-ceilandia-1709',title:{rendered:'Lula participa de ato de campanha em Ceilândia'},excerpt:{rendered:'Presidente e candidato à reeleição cumpriu agenda eleitoral no Distrito Federal.'},date:today,published_at:today,created_at:today,category:'Política',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/foto-oficial-do-presidente-da-republica/foto-oficial-do-presidente-luiz-inacio-lula-da-silva/FOTO_OFICIAL_LULA_2023.jpg/@@images/image',href:'https://www.brasil247.com/brasilia/lula-faz-ato-de-campanha-em-ceilandia-ao-lado-de-leandro-grass-kokay-e-leila/'},
    {id:'flavio-1709',slug:'flavio-campanha-1709',title:{rendered:'Flávio Bolsonaro cumpre agenda de campanha no Nordeste'},excerpt:{rendered:'O candidato à Presidência cumpriu compromissos eleitorais no Ceará e em Pernambuco.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5894.jpg',href:'https://www.cnnbrasil.com.br/eleicoes/no-ceara-flavio-ignora-ciro-e-diz-que-pt-trava-desenvolvimento-do-estado/'},
    celinaPost,
    {id:'michelle-1709',slug:'michelle-senado-df-1709',title:{rendered:'Michelle Bolsonaro reafirma candidatura ao Senado pelo Distrito Federal'},excerpt:{rendered:'A candidata divulgou posicionamento sobre a disputa ao Senado no Distrito Federal.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www12.senado.leg.br/noticias/materias/2023/03/21/michelle-bolsonaro-participa-de-sessao-no-senado/@@images/image',href:'https://www.itatiaia.com.br/politica/michelle-rebate-sebastiao-coelho-nega-deixar-senado-e-diz-que-e-candidata-de-bolsonaro/'},
    {id:'leila-1709',slug:'leila-senado-df-1709',title:{rendered:'Leila Barros disputa a reeleição ao Senado pelo Distrito Federal'},excerpt:{rendered:'O Distrito Federal escolherá dois senadores nas eleições de outubro.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www12.senado.leg.br/noticias/materias/2024/03/08/leila-barros-destaca-avancos-e-desafios-das-mulheres/@@images/image',href:'https://www12.senado.leg.br/'},
    {id:'bia-1709',slug:'bia-kicis-senado-df-1709',title:{rendered:'Bia Kicis disputa uma das vagas do DF no Senado'},excerpt:{rendered:'A deputada federal concorre ao Senado pelo Distrito Federal nas eleições de 2026.'},date:today,published_at:today,created_at:today,category:'Eleições 2026',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www.camara.leg.br/internet/deputado/bandep/204374.jpg',href:'https://www.camara.leg.br/deputados/204374'},
    {id:'julio-1709',slug:'julio-cesar-paratletas-1709',title:{rendered:'Projeto de Julio Cesar Ribeiro prevê aposentadoria especial a paratletas'},excerpt:{rendered:'A proposta estabelece regras para aposentadoria especial de paratletas de alto rendimento.'},date:today,published_at:today,created_at:today,category:'Congresso',categorySlug:'politica',categoryColor:'bg-red-600',featured_image:'https://www.camara.leg.br/internet/deputado/bandep/204372.jpg',href:'https://www.camara.leg.br/'},
    roneyPost,
    paulaPost
  ];
  const isMaceio=(p:any)=>/maceio|alagoas|pajucara|ponta verde|praia do frances|maragogi|sao miguel dos milagres/.test(norm(p)); const maceioPosts=posts.filter(isMaceio);
  const categories=[{title:'Política',category:'politica'},{title:'Distrito Federal',category:'distrito-federal'},{title:'Economia',category:'economia'},{title:'Turismo',category:'turismo'},{title:'Gastronomia',category:'gastronomia'},{title:'Saúde',category:'saude'},{title:'Tecnologia',category:'tecnologia'},{title:'Esportes',category:'esportes'},{title:'Internacional',category:'internacional'},{title:'Cultura',category:'cultura'}];
  return <div className="min-h-screen bg-gray-50"><Header/><main className="pt-16"><TrendingBar posts={posts}/><div className="pt-4 space-y-4"><SponsorBanner sponsor="petrobras"/><div className="max-w-[1400px] mx-auto px-4"><TopStoryBanner href="/analise/stf-fachin-gilmar-mendes" kicker="STF • JULGAMENTO EM ANDAMENTO" title="STF diante do espelho: a análise de Paulo Fayad" excerpt="Fachin conduz uma sessão institucionalmente delicada enquanto divergências sobre o caminho processual expõem a tensão interna da Corte. Leia a análise de Paulo Fayad." image="https://static.metricool.com/planner/202609/6885599-file-14133517272000082486.png"/></div><SponsorBanner sponsor="snaider"/></div><div className="mt-4"><HeroCarousel posts={heroPosts}/></div><InstagramVideoBanner/><div className="bg-white pt-8"><div className="max-w-[1400px] mx-auto px-4"><LatestNews posts={posts}/></div></div><div className="mt-4"><PremiumBanner variant={0}/></div><div className="mt-6"><SponsorBanner sponsor="visao"/></div><ViralStrip/><MosaicHighlights posts={posts}/><div className="mt-6 mb-2"><PremiumBanner variant={3}/></div><div className="mt-4 mb-2"><SponsorBanner sponsor="lunardi"/></div><div className="max-w-[1400px] mx-auto px-4 py-8"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-10">{categories.map((c)=><CategoriesSection key={c.category} title={c.title} category={c.category}/>)}</div><aside className="lg:col-span-1"><div className="lg:sticky lg:top-24"><Sidebar/></div></aside></div></div><div className="mb-2"><PremiumBanner variant={1}/></div><div className="mt-4 mb-2"><SponsorBanner sponsor="coreto"/></div>{maceioPosts.length>0&&<MaceioShowcase/>}<div className="bg-gray-50 py-8"><div className="max-w-[1400px] mx-auto px-4"><InterviewsSection posts={interviews}/></div></div><div className="mt-4 mb-2"><SponsorBanner sponsor="kumon"/></div><div className="mt-2 mb-10"><PremiumBanner variant={2}/></div></main><Footer/></div>;
}
